// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCI4fdaQlc2wV42FQKOBH4Bw7NEL_rRbc',
    appId: '1:698640174436:web:946a937e08b93518b1fe71',
    messagingSenderId: '698640174436',
    projectId: 'tracker-2022',
    authDomain: 'tracker-2022.firebaseapp.com',
    storageBucket: 'tracker-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAon16MHeb42PJqrW-41YMnWNwarnasF8',
    appId: '1:698640174436:android:d1c0ea163c682baeb1fe71',
    messagingSenderId: '698640174436',
    projectId: 'tracker-2022',
    storageBucket: 'tracker-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUO5YucND6qz_8lt2VUh5pQ8sTqZGwKq0',
    appId: '1:698640174436:ios:a644b459ea051c78b1fe71',
    messagingSenderId: '698640174436',
    projectId: 'tracker-2022',
    storageBucket: 'tracker-2022.appspot.com',
    iosClientId: '698640174436-ao69fsnjkjmmmb9b63qujcnkrhsa8as1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUO5YucND6qz_8lt2VUh5pQ8sTqZGwKq0',
    appId: '1:698640174436:ios:a644b459ea051c78b1fe71',
    messagingSenderId: '698640174436',
    projectId: 'tracker-2022',
    storageBucket: 'tracker-2022.appspot.com',
    iosClientId: '698640174436-ao69fsnjkjmmmb9b63qujcnkrhsa8as1.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackerapp',
  );
}
